---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 23 * * *
  restic:
    pruneIntervalDays: 14
    repository: ${APP}-volsync
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=300Mi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
#    volumeSnapshotClassName:
    retain:
      daily: 12
      weekly: 1
      monthly: 2
    copyMethod: Snapshot
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
