apiVersion: v1
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:A9gqiCYwiBd3m5yIEliqXVAioj6FDB/yCi4eZg6ioetAJzAo85MnQuwipJd7qEg+XNDKPaHdqIpl32ik7NjyuLU=,iv:myFAYu0kux7vczUGOJODkYyd2S+JCl6cHxAyr/5arjw=,tag:0z3hKN+plTZjzeeSk6TRNQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:XdTayoH23751Ht+E1eO5z/pHp9/7/EAQC+asVk0fLiU=,iv:KPDBfBwiFpMnD8DDRbhwqLGykM8mgK2hq+u3g+kMqug=,tag:YruKcw4Yu/ZS7zeULU3lqQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ld5HV5D2GVf7mk+RMNOaCwT+e9SljAzHDFeIuH8kQks=,iv:VpE/8zQPXKUTABMdnc+dp4aIgdnFX+X4IJ69xdSR8go=,tag:6ZXtwyhU1R86/wlNb/2CnA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mgPEJLuWW+r3CQ7+GRcSQFTExk0tOvoehXmaMT3KxFQ=,iv:Z5rIo4n97tgJ0IV+hpUyuU6TTov9i5lZAguCVuJCHyI=,tag:LMGRCQf5wmoDwc+3KsO32w==,type:str]
kind: Secret
metadata:
    name: ${APP}-volsync
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUnhpNHl1WE5mbUhKYmN2
            QTdORFJ4Q25TRWE1UElud0tqRG1UQ1BLalNBCnAvcFk0YWNHQXk1ZmVxOUl2cFdG
            bUFnTUxacHFyR3NsU2hKMXVmTTJjOWsKLS0tIGZPWlM5L2tYeTZrWVdvQTNDV0Vp
            eVBIejZ3cFhReTgrOHdhNkk5dVkxM0UKNnCZzzZ9Nzahhc017nlYK3xMHeiojXeP
            5dnliy4aLpZrv4a9GOXS9tczMMBml/ElvFk2LoB+x56hV0HQdjNiMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T05:39:18Z"
    mac: ENC[AES256_GCM,data:LMZN8idoUz/kZ1AQSFgWhIt5nW+2o5ILPdUEBhsGVttaQGXmxyxhq1tl8AG+L4Pny9ph4f5uOk4VWzxyMaCOCLFiC7cvhsN5Gpl/yPcVJwEATFT6EQSnwnnVq9rZSRB/NB9XF9I4wDY1M/P0vqyyZLQeXimBCMngCrX5RurAQpk=,iv:/ajgGD0+2jlqLaWzSTJ59lcCLeDbaEtGx1lEArsB6T0=,tag:JfaO7slLkFfHNF3qsoQSvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
