apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 1
  # disable pod disruption budget for oracle single node
  enablePDB: false
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
