# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 1
  # disable pod disruption budget for oracle single node
  enablePDB: false
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ovhcloud
  storage:
    size: 1.5Gi
  monitoring:
    enablePodMonitor: true
