apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ovh-backup
  namespace: authentik
spec:
  cluster:
    name: authentik
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
