apiVersion: v1
stringData:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:+A5bhdwK0W9QS67is4U04/pkJFvH36uhqzFnsHHQh0uIqa49ZLCuOA==,iv:VbOZh603J81qXTPyW9wvf0L5XOI6WMKxi86P3OwMdzY=,tag:m3ab5JyTNQJLz+RwNV45tA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:Ylqp,iv:IU3xCun1V5uv3f1MP4V/G0HShnGwd5Sf5bId+twg494=,tag:qpKLdRBaqeFrKLvKg7M9vw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:dkIB,iv:TVdglRB4Cme2WyA4ZuSdLmmCsaRaOuOAvlSVCKpiugY=,tag:ilayWv5pFvECXb3EjFNRdw==,type:str]
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTlRLcFJMTGh0WU91cnVP
            Ymx1Uk5USlRlR2dpd0R3M1hkMzYrYkhnMHhNClNDbGZpdUlWQWpkV3h6akVud21U
            VXUyY3dYZlE1UE9aWUxtTWNxU3FDbEUKLS0tIEEvMXZDbEhsRnhud3diQkFzcGo3
            MURsQU02TUc4bG5SNXJYQkluWUJ0bjQKLYoUo8rD4JJDNXdllXG+B45P+txxrXGj
            PqqWcRA3Bg63qc2Y+Qre1SbrcBmulLldwyOPHXyYI8yInfyzi7vb/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:48:27Z"
    mac: ENC[AES256_GCM,data:KYy88+yczP0tSd6c3E6HNg3yozNa3C8jfBz3vTnXYQKkVePNSFU3zQIZWYJMRHnc3xDD0moKuXILWGxMnXQ3Xb8gTFMqQ7KUyRBRPf/TICF9W+LmoTnlDHdN33ITmuEX6hHpPybQ0iOwN23VvOC9mUSjX27qdUZxjwSXnYhfuDM=,iv:Fv55c33zHrXPaVGwCqT/fJsRxszuXU6wYVrTa8JX4Ac=,tag:vFs6s7cvgPDP340/SltmkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
