apiVersion: v1
data:
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:HYORX7uADh4EhebdfW0g9arbWMb8QvoAE2vbifCrqDyBMiwWf3RSu2TnuGHLmZZKsTCRAQWL9QQ=,iv:Ow17MOwgfhQ1ZaPbWm96aeoYx/WqGalbfgwE/7l0ivE=,tag:d2cZ6GMTTpbL3TtUvHkI2Q==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:4aALNOcVyRtEDBkw,iv:ltJvEQr+ytutOvBC185eOiC7w+N8t0EEaZ+YezSAugk=,tag:hMF6rxq6eQk2kjQDs06SQQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:Y7o4fOSxzHnNeu3E,iv:o4g75WmHZnm5cZHGFsuTlExeFd6+mV8rJnBT5KAuwB0=,tag:cP+F88O7shLmCBAoeClfCg==,type:str]
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTlRLcFJMTGh0WU91cnVP
            Ymx1Uk5USlRlR2dpd0R3M1hkMzYrYkhnMHhNClNDbGZpdUlWQWpkV3h6akVud21U
            VXUyY3dYZlE1UE9aWUxtTWNxU3FDbEUKLS0tIEEvMXZDbEhsRnhud3diQkFzcGo3
            MURsQU02TUc4bG5SNXJYQkluWUJ0bjQKLYoUo8rD4JJDNXdllXG+B45P+txxrXGj
            PqqWcRA3Bg63qc2Y+Qre1SbrcBmulLldwyOPHXyYI8yInfyzi7vb/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:14:44Z"
    mac: ENC[AES256_GCM,data:FRQ+tar8E6xg519t5ReGLe/mV4oIvwmyjiWUzq1R7d0Ni93xFVAfBadIVd3KvR+GYRmsP6LnkyFky4DxXgThHRULP+taFphPDHOxZVmCkm32AWayPIeG/hriXrC0fEhmfX+U48QlFf35C9OgZa1w8UhuhGfjNLkTpVVKVHa2Ry4=,iv:SFMXByjZgZrB4v8CFE5f/H6QYznRtYeQW4gE+7VymTg=,tag:y2li3Y5XZvRRLE/clveAEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
