[env]
KUBECONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/kubeconfig"
TALOSCONFIG = "{{config_root}}/bootstrap/talos/clusterconfig/talosconfig"
SOPS_AGE_KEY_FILE = "/home/rize/.ssh/key.txt"

[tools]
sops = "3.11.0"
talhelper = "3.0.45"
