apiVersion: v1
kind: Secret
metadata:
    name: librespeed-oidc-client-secret
    namespace: homelab
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:Crjn1v0xViL8R2pM2caiM2WAmXjEDZpgLqAx+6MIKLg=,iv:CRBMw4oAhF5JcSmV0gm0Ev/WIndWU8TbhHhUcG+mjgA=,tag:j4t1gfXv41NXswg8UH86Xg==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cjhjVy9NUHRYZDdmZlNB
            am4yS2ZaK0ZqWmJQWkk2eVVxYUNJY01YYUh3CjhYemttRmZjbVB3TmtYME1GZ2Jr
            My9QWEM5blI1YXVqZHFKUG9JNGpwVW8KLS0tIEZtYXNMTzh3S1hHUHErbnY2NUxM
            QWwzc0xidERrRmlWOS82RVczOU1ENUUKIbYB99OyeZ77YFdo7Qlsy5OGCnfN3IMT
            7d4WQFErsDylf3ZUK+DucuKkssPDCqKlQIdzeUlEmrEtQ/U7ILFZWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T05:25:32Z"
    mac: ENC[AES256_GCM,data:HY0w+CBuqldLP+lG7mYSzZfGPMrrP+jStueF7r8JJykEemBu7pmFHOlD9EyZTcGKVQfPMfbMIVWQMdT9D3qvUscVqOAOFA+elbJ8qhqteCyJUSDwswkdvKYPX1tVdCYl6yP71dkPUD1d41BGdFLB5rZZY7IHtERBI3MG8jiXLnI=,iv:YwbzTO7s/fqXruQN5gNaMU3raccTqDM1IOdxdP2Ap6E=,tag:s3eP99TTi0RsYaY38eW6Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
