apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - sabnzbd/ks.yaml
# Disable qbittorrent on Oracle
  - qbittorrent/ks.yaml
  - recyclarr/ks.yaml
  - jellyfin/ks.yaml
  - jellyseerr/ks.yaml
