apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ../base/arr-stack
  - ../base/librespeed
  - ../base/homepage
#  - ../base/jellyseerr
#  - ../base/audiobookshelf
#  - ../base/qbittorrent
#  - ../base/jellyfin
#  - ../base/radarr
#  - ../base/sonarr
#  - ../base/recyclarr
#  - ../base/prowlarr
#  - ../base/sabnzbd
  - ../base/keycloak/ks.yaml
#  - ../base/mealie
