apiVersion: v1
kind: Secret
metadata:
    name: airvpn-wireguard-config
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hSbFiBDW+Eps/F+Ve5jAY6WVFPiWBCh9W/IlVL+jCPjda/5JpH4fPOw8ffg=,iv:l+eiwj5WmnRkz7BQzEYRM9vNhOAF7wXXhOfEJfd0GFw=,tag:Pkq7zRoLN3iW0yxWrKCjbw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:8zrR/2wdg/TusMwwv/PJem5eX8ladjIRySfJw448GnlM7uduc7g+o6Ncu3U=,iv:z3VQ3TyZJRFlZpnxMQMPdvjsN+ZH7K/6+RznHFqWYlk=,tag:+SePjNI5e8wJIzcN9BTkWw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:6qQyW1E49FXB/DzqUqrAlw==,iv:KaQhsfm7ouU6iENPyI2vZUAKP+4FbcuBwJcrM/e597k=,tag:pR1AQEEd8RR8g8SeDTXesA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:P5xByaVXRp0f5m8hnkvDOhMgoNSUPNPSrPRnABydaC6WLm1LcI5R6I5Q/H0=,iv:z/NffaLRKkqJa+irxdHMWznZryA8g8g/ldHKNQYCTns=,tag:49wMqTz4oEGZNGI5bEMXIA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVpFTitYczVmOG1OL1Ev
            MUlZVjFGVWVGK1BEeDlyZW1WVFlXZVRWdjNVCnhRWXNqbEhoYUZGSXZ2M2dSM2Fx
            S2NrM3hyNFNSUUxyazdTbnYrMjd3THMKLS0tIEphOHRoNldJNDBsbUVIQ0xaT3RE
            YkNkcHROdjFxMzVoY1pXdklkNzhVWlkKuRki4jC5XWpoV8Pxy6eFwI4svyHXpCaX
            /ZDHhXLRjkGzWs6xDYVaAPpIHKu6MsDcvy5Ld/ew42+1VWppuHZYsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T13:44:42Z"
    mac: ENC[AES256_GCM,data:TDVH+E9KZbF3VeCb7x+APxLuoWWxSjFx0XxJ6HopYXn26AvZmV+Csy3aKPTyxXB054lTkViufNjviPmppoWmcCGQI5zwcEo3iZVktNkLUnD2EKwVWhfL7veznQMlPo/xF48xeKU9zb5xT46Mrgg8F+0AnkVjVOQ1A7II46MkL7g=,iv:P9SC1aTpkTHWPzMHhmvLOAzJIzR/swfJa+398IoPz6w=,tag:psvB5ZqAir8FaU7/ITyPnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
