apiVersion: v1
kind: Secret
metadata:
    name: airvpn-wireguard-config
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hSbFiBDW+Eps/F+Ve5jAY6WVFPiWBCh9W/IlVL+jCPjda/5JpH4fPOw8ffg=,iv:l+eiwj5WmnRkz7BQzEYRM9vNhOAF7wXXhOfEJfd0GFw=,tag:Pkq7zRoLN3iW0yxWrKCjbw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:8zrR/2wdg/TusMwwv/PJem5eX8ladjIRySfJw448GnlM7uduc7g+o6Ncu3U=,iv:z3VQ3TyZJRFlZpnxMQMPdvjsN+ZH7K/6+RznHFqWYlk=,tag:+SePjNI5e8wJIzcN9BTkWw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:6qQyW1E49FXB/DzqUqrAlw==,iv:KaQhsfm7ouU6iENPyI2vZUAKP+4FbcuBwJcrM/e597k=,tag:pR1AQEEd8RR8g8SeDTXesA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVpFTitYczVmOG1OL1Ev
            MUlZVjFGVWVGK1BEeDlyZW1WVFlXZVRWdjNVCnhRWXNqbEhoYUZGSXZ2M2dSM2Fx
            S2NrM3hyNFNSUUxyazdTbnYrMjd3THMKLS0tIEphOHRoNldJNDBsbUVIQ0xaT3RE
            YkNkcHROdjFxMzVoY1pXdklkNzhVWlkKuRki4jC5XWpoV8Pxy6eFwI4svyHXpCaX
            /ZDHhXLRjkGzWs6xDYVaAPpIHKu6MsDcvy5Ld/ew42+1VWppuHZYsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T16:55:14Z"
    mac: ENC[AES256_GCM,data:9VnEUzAU742s9axGHFWZSPBE7SCCuqofCkyEYrVDdW8bBtajFBb3J5i7c53SSuVHFxAgyVEL5TsB4KCfjzr74/xmWKVasr5V30/CzqIUlK/CWLIooD+BBbSa4yxn+y2FFhXARe4NW8SzyhnmaUcVc0+cBNuNdemJHhAjX7VXTew=,iv:0XZE+RdwRIEZbDm1BxdJx+d0rZt6WefEA6eXQSIH/pE=,tag:+Uut6uH/dc0HUUTIVpsqyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
