apiVersion: v1
kind: Secret
metadata:
    name: airvpn-wireguard-config
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hSbFiBDW+Eps/F+Ve5jAY6WVFPiWBCh9W/IlVL+jCPjda/5JpH4fPOw8ffg=,iv:l+eiwj5WmnRkz7BQzEYRM9vNhOAF7wXXhOfEJfd0GFw=,tag:Pkq7zRoLN3iW0yxWrKCjbw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:8zrR/2wdg/TusMwwv/PJem5eX8ladjIRySfJw448GnlM7uduc7g+o6Ncu3U=,iv:z3VQ3TyZJRFlZpnxMQMPdvjsN+ZH7K/6+RznHFqWYlk=,tag:+SePjNI5e8wJIzcN9BTkWw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:6qQyW1E49FXB/DzqUqrAlw==,iv:KaQhsfm7ouU6iENPyI2vZUAKP+4FbcuBwJcrM/e597k=,tag:pR1AQEEd8RR8g8SeDTXesA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVpFTitYczVmOG1OL1Ev
            MUlZVjFGVWVGK1BEeDlyZW1WVFlXZVRWdjNVCnhRWXNqbEhoYUZGSXZ2M2dSM2Fx
            S2NrM3hyNFNSUUxyazdTbnYrMjd3THMKLS0tIEphOHRoNldJNDBsbUVIQ0xaT3RE
            YkNkcHROdjFxMzVoY1pXdklkNzhVWlkKuRki4jC5XWpoV8Pxy6eFwI4svyHXpCaX
            /ZDHhXLRjkGzWs6xDYVaAPpIHKu6MsDcvy5Ld/ew42+1VWppuHZYsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T14:50:51Z"
    mac: ENC[AES256_GCM,data:H5l2GCuSlRyds3NfdkiF0opp7lzBqE4r07r3eOExiFMG3AIjaRnYeicv+1xf0hLafR6MG3IimjqPpg/UiDgOY+EhHUlE9Uhc7FHiLvEeZeVClN3wV6spIL0R41iu7rAmAaREn09rYeEqyZDVA+kny/dL3FiUFvbXXKXAJHj7X4g=,iv:S/peXKmmeCc5RlXpZCiPfg7rJnWuFw3F5Up1Oo2sJWU=,tag:vy7eWncjvR6rF+OQ3FGqjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
