apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secrets
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:e+kW31EDnL5DeKM13p314hIPVHMwOahUNJrQ19DIxtgA9qxmBLj6Q9icuNU=,iv:J9knoqXg0QxAhxVp7Nnsk1EtPdznXdsMmUFyrmc1l/Q=,tag:RhUnavCgy6wKQP28+vp9MA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Sj6KU4HnN+0hj5liAWMJZ0grKhkFDPxlCOGGXDbXmUZKRYhCvx+W4XO4eew=,iv:PbymibUZJnmlXlzeAnskOkxIFUfG5HzMdbAnAQ8euiY=,tag:MkVa6ARvwmlcvt5n+gQoNQ==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:lF6rd9g=,iv:RlhWpu9N4G3Jl0WqAeDXeQ19Bepq07Agga6LL3N/8Pw=,tag:mLhb4StyqNibU7pCbmZCuA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:WZ/KR+wyvBkASgvS,iv:ujZTqCFi5eYLk5CsCXh0IwWjUtUt6R8QUip5ndgG1Dc=,tag:Chn12+gxcmUHEgaCK6s8RQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:8vPcYSzbVOQEFvumCg==,iv:tyA40aVHwO41wHvusNQ9UtmO7x5sMVs+D8L1XF171Fo=,tag:yi3CmMYSSF9hZf5oiBi2jw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:AnNSoC7KWGcLfwULU8v9gslmRCOjZyRmiHtr6afILgTDQlHicQKT8EXVxFY=,iv:FPlQBSMguN4UByw0Nyqra1aQP//9eGK43jzxrWyL4Lk=,tag:0JBFtg5HIG/Tu8yNoM3/RA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVpFTitYczVmOG1OL1Ev
            MUlZVjFGVWVGK1BEeDlyZW1WVFlXZVRWdjNVCnhRWXNqbEhoYUZGSXZ2M2dSM2Fx
            S2NrM3hyNFNSUUxyazdTbnYrMjd3THMKLS0tIEphOHRoNldJNDBsbUVIQ0xaT3RE
            YkNkcHROdjFxMzVoY1pXdklkNzhVWlkKuRki4jC5XWpoV8Pxy6eFwI4svyHXpCaX
            /ZDHhXLRjkGzWs6xDYVaAPpIHKu6MsDcvy5Ld/ew42+1VWppuHZYsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T13:54:44Z"
    mac: ENC[AES256_GCM,data:9BdiTlk11tj8GV9P7Uo6SnHR0umGWu89r8y5ilzjpdSbveCjT99hyga4mXMBTIOmY8jOz8zoicPn4CcrnNt+woFhm6AkcpKZfYkRXVS04ghjQICMKCNMkgvPtpzmzEDhOozmA3FKDPhwDTRHgpzn2gmY8Serfow22rsrd7eNR0Y=,iv:oGMeqB7iDBlvoGwZcLpvDwICbTpEg/y3yeKrRRCfjng=,tag:840IERy7BB3Lnk5nfzoxyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
