apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup-key
stringData:
    NB_SETUP_KEY: ENC[AES256_GCM,data:8J9WS4LH+z4eAYykLv7NtGVsKPi9OvCm3p3DTxBJAdBPpvWG,iv:zKP1+0kqP/QRMm+8yPs33T47a6MJ+kPa95BVaDaLHwU=,tag:HIvrN3NHcSl6OyYoUNghbA==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTEtCU1gyM3hhUUV4Ukll
            WkYwSWk5TWtnWUxZVDIvbG4vL3ZKdjNqVUZ3CnVITDc4VytyTTFWUStQUzlOQmRk
            QU9US0JEVGFmRVpKcDd0cTIxcXphdlEKLS0tIHA1Zy9DeitZZ3RNNTl3bDRZQ0dq
            cXlaWFl4ZWRiV2lPckZvYk5IUzA1NEEKZfn63dnYoLR1izJRGE9dl4XODUK38Rvn
            X86jmCC6CXphzU0sE7A1aVOTW+5kWr+Kh9ujt73e6OUHfMTMBEfkRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T04:51:12Z"
    mac: ENC[AES256_GCM,data:FuaGFDFoqiRZSP1h3/72omnkHCSDQOvMIWCFzZGr4yDUxzOJBFcayQ8NdnMGiSf4ptQiJwzTo2/PfPySSKi8qa1wY7yxpqPnjco2v2WYYKWsszdGbep+5OniH96VeVRowTNgKm4rIDVfus7v703vi91dmmT7Vfg+IRcFsWDPGiA=,iv:UQrjJk+Fe18C2tpJLy17wOUhpWJ5AeYtY9aWNJCbf60=,tag:AbPoiGhhVlbDEG3JcPQgsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
