apiVersion: v1
stringData:
    client_id: ENC[AES256_GCM,data:Hllag1i1CRYJlFq3StqniQvNfuxHdl7jjNyiEP5Gm3HsTRyT1bS31w==,iv:jPQWY1WPVnTRdKofmUz8WljCVLJ4GsZTnMRFprp/ZoA=,tag:38c2IwTE+R2aERm27XQIcA==,type:str]
    client_secret: ENC[AES256_GCM,data:CLBHqBNQU5/vMk+P/fY5JlW+KCb8hAcOvgvECYtt+Dj6PZuy0HJtpzpSAhgbPWKSFZvq6tq3mXUSWRB+2w7oNd3IuNy7fJVXvLB1TFoYJi5XKxGTF/MuMxtggQHvKwt5cn0IsGpxg2K1iHEzcC6tAAFZDdE8ZbnB4HzTFsOGU2g=,iv:pftjFLPDumvxXCkkfRDLxc4duETZlDa2scGezGIecAc=,tag:rDHxJhyO+/srSimtbmpFwQ==,type:str]
kind: Secret
metadata:
    name: grafana-oauth
    namespace: observability
type: Opaque
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVUt2azE4OWl5TFB4Unlj
            ZFZyanBySjhaNDNIYm0zTkU2Skx4WXJsZWp3ClJOOC9ya1ZGWkRVSXVrMldFVTRV
            aTlCS2IzUW5OY3VPbnJlb0dlS2FqUlEKLS0tIHBHWVBJSVUxVHk0OGdwZVZEV0Fk
            anE3K0YrMmpkRkFaK3F0czIzN1R2anMK3FoGfj9UH8Itjzsy7d8chb24I8yYKCxr
            rXKXA6hc56MIujQQlZNc4bYGkVRWMtvNgIg/CF0Eh281WaCUJnnYlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T08:33:15Z"
    mac: ENC[AES256_GCM,data:Y6D9oSD2jYNrGGSXwdXE4d4HWCx1fExyIhPCf86shhziANa8sMsbxoZ7+KeuA9nEjYkGfKfkre2o/pknb1gZwYS/7aUdeVndu7ohM4SJvAEvq0L9nKzirUZfoGAnU+03yIIa9LTRbebkz1NLzhkmXGOUcd6ftx8iVAL38yeyih8=,iv:oh9FBQtHkjTKA6rU9LCwpZbCds7gG5/cZkC4C9no9U8=,tag:B0MXGIn2OrLcP9ugyPlvZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
