apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoyproxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - certificate.yaml
  - clienttrafficpolicy.yaml
  - vmpodscrape.yaml
  - grafanadashboard-envoy-gateway-global.yaml
  - grafanadashboard-envoy-proxy-global.yaml
  - grafanadashboard-envoy-rate-limit.yaml
  - grafanadashboard-resource-monitor.yaml
