---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - objectstore.yaml
  - secret-authentik.yaml
  - cluster.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - scheduledbackup.yaml
