---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ovhcloud
  namespace: authentik
spec:
  configuration:
    destinationPath: "s3://rizexor-oracle-postgres"
    endpointURL: "https://s3.ap-south-mum.io.cloud.ovh.net"
    s3Credentials:
      accessKeyId:
        name: ovhcloud-s3-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: ovhcloud-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
      maxParallel: 8
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "31d"
