apiVersion: v1
kind: Secret
metadata:
    name: ovhcloud-s3-credentials
    namespace: authentik
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:2TlIX+f0snjLUt/ewdN24Zcf2deHYfxcb27RyOD7+JU=,iv:yiczyb5tlUBp7iAHbqfbm6x9rJS5rSgB7VHsMjlHkfQ=,tag:5MUhdyTYFN7TIDOXTwE5Bw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:teRaAsFLbZTDOOSoxGXY9gy5qLcdl+covmQd528aEWA=,iv:RzyiGzFBhW5PV3FOBmmewzDwzuRi3o7MtZ7XGznR1p8=,tag:vXgcYHqSJ0shBrXLJw/RFw==,type:str]
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZmU2Mm1UcllNdGhoS2xQ
            NVJ1UkhkQ2FBT2lPWEVubVYvZ3BHYUJDZXlzCjVFQzVxTXd6UXlsQXZDYVI2aVFu
            dEo5cUJMN1JsMUhnTDAwaW1VcktBZlEKLS0tIDFsV2g2U3pVQ2lNWGtGeFdGR2RT
            NFMvTERobWNKR3pzUUROa2dnVFE0ZkkKxhj4uIUcjdLCZEfcOLDesIvPPfurhg6r
            /paGkgTOREzRME5TJOgj1a2qQRh0qQnsJFSJ2NHHINZf+2nOI+nXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T14:29:16Z"
    mac: ENC[AES256_GCM,data:Ff3dH++K2kAIpe+ZPV1exd7YsL3FHHxtcb2yq8JpykP+2c5dyvXOr5aPoqep4dOo+9+cCmiXZEtR2Ii6G4C+ip/kPCmzh4E5kfxuajyJJ2cJo8pcJltrFQj71JlfIh96J1PeVnrJnbMQBGJgRNjtHlXj2fA+iP8OZzLPzlq/QCw=,iv:nycWvwA5Eeuk5M8QitrnVrTjinQbCgyb+pIDOARAxVI=,tag:GBKF8Tyi5ch9pgNLw++rYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
