apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
      signout_redirect_url: "https://authentik.${DOMAIN}/application/o/grafana/end-session/"
      oauth_auto_login: "true"
    server:
      root_url: "https://grafana.${DOMAIN}"
    auth.generic_oauth:
      name: authentik
      enabled: "true"
      client_id: "$__env{AUTH_CLIENT_ID}"
      client_secret: "$__env{AUTH_CLIENT_SECRET}"
      scopes: "openid profile email"
      auth_url: "https://authentik.${DOMAIN}/application/o/authorize/"
      token_url: "https://authentik.${DOMAIN}/application/o/token/"
      api_url: "https://authentik.${DOMAIN}/application/o/userinfo/"
      allowed_groups: "Admins"
      groups_attribute_path: "groups"
      role_attribute_path: contains(groups, 'Admins') && 'Admin'
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              readinessProbe:
                failureThreshold: 3
              env:
                - name: AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oauth
                      key: client_id
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oauth
                      key: client_secret
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: credentials
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana
      strategy:
        type: Recreate
