apiVersion: v1
data:
  recyclarr.yml: |
    # yaml-language-server: $schema=https://schemas.recyclarr.dev/latest/config-schema.json
    radarr:
      radarr:
        base_url: !secret radarr_url
        api_key: !secret radarr_apikey
        
        quality_definition:
          type: movie
    
        quality_profiles:
          # HD Bluray + WEB (1080p)
          - trash_id: d1d67249d3890e49bc12e275d989a7e9  # HD Bluray + WEB
            reset_unmatched_scores:
              enabled: true
    
          # UHD Bluray + WEB (4K)
          - trash_id: 64fb5f9858489bdac2af690e27c8f42f  # UHD Bluray + WEB
            reset_unmatched_scores:
              enabled: true

    sonarr:
      sonarr:
        base_url: !secret sonarr_url
        api_key: !secret sonarr_apikey
        
        quality_definition:
          type: series
          qualities:
          - name: Bluray-1080p
            min: 2
            max: 6
            preferred: 3
        
        quality_profiles:
          # WEB-1080p
          - trash_id: 72dae194fc92bf828f32cde7744e51a1  # WEB-1080p
            reset_unmatched_scores:
              enabled: true
            qualities:
              - name: WEB 1080p
                qualities:
                  - WEBDL-1080p
                  - WEBRip-1080p
              - name: Bluray-1080p
          
          # WEB-2160p
          - trash_id: d1498e7d189fbe6c7110ceaabb7473e6  # WEB-2160p
            reset_unmatched_scores:
              enabled: true
kind: ConfigMap
metadata:
  name: recyclarr-config
