apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-system.yaml
  - topolvm.yaml
  - variables.yaml
  - homelab.yaml
  - homepage.yaml
  - snapshot-controller.yaml
  - authentik.yaml
  - cert-manager.yaml
  - envoy-gateway-system.yaml
  - observability.yaml
  - volsync.yaml
