apiVersion: v1
stringData:
    client_id: ENC[AES256_GCM,data:vuTrmQr1TuTyq7fxeCg1YjFlBLhtVP5QDruUUZAV8QOHRtrk/Jacbw==,iv:PaT25cAFCBrOCwnN7qXFQSK7VSUCP1Sc58YKrA7yiRU=,tag:KWOW3MQW500s+DhZrtrrbg==,type:str]
    client_secret: ENC[AES256_GCM,data:dw/VxzIf+g1uEH189GdfNvDbD05p4l4gMXx32xkTBipwlBRgMCMw6qf0vVr3FY+TGq4q8oeVXsFKyXVBGNONRc/gleWeZrv1xFqNWKcl1KS+Kk8k8pkK0ZJA1r1HVMF1L5c7uoszNjSMTV3423YUzB/ByvXMzGiImBIV79RlXy/8,iv:89lWgLfL01is7g+1ZUlYQR8+xzRr3SSkYKTZ22Pc90I=,tag:cmcqLEoWhCvdru+5g4aynQ==,type:str]
kind: Secret
metadata:
    name: grafana-oauth
    namespace: observability
type: Opaque
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVUt2azE4OWl5TFB4Unlj
            ZFZyanBySjhaNDNIYm0zTkU2Skx4WXJsZWp3ClJOOC9ya1ZGWkRVSXVrMldFVTRV
            aTlCS2IzUW5OY3VPbnJlb0dlS2FqUlEKLS0tIHBHWVBJSVUxVHk0OGdwZVZEV0Fk
            anE3K0YrMmpkRkFaK3F0czIzN1R2anMK3FoGfj9UH8Itjzsy7d8chb24I8yYKCxr
            rXKXA6hc56MIujQQlZNc4bYGkVRWMtvNgIg/CF0Eh281WaCUJnnYlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:38:16Z"
    mac: ENC[AES256_GCM,data:awvzw6cyFTHzidTP9gQ1Zrgbo++bFzkLr+cx+EatpQDrXKg6h+TlXhhW9crf6T4mwrYo7DxRISEojkbtXdZrA9Qo5WTEkUaKbPHqgFWk84d5xXsCb3JX5Vx+XNuCqOgG4fvV/hSNFVxFs7NJaslRk1Kv2E0Dy8FuKIrzbPwzA8A=,iv:o3EuuRzOeFMfD7x3uJ4j/SCb8O89BUAhqRJbNf9Ax4w=,tag:/tG4BH1MHGPzvLTo8lO40Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
