apiVersion: v1
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:IXGxFITGFM0r5UYh3Mz1FbSqUgJLjQfxfUk=,iv:fFYinMddIeb9jWHgbTrbYe4MI0pd+MiphHAxDOS4VhY=,tag:SgdBQDAyZnUJHhraQnBUpA==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:r/5T7g==,iv:rbVHJidkFhT21vGrWP2J3VwtN298aWTimyxZK1wghUU=,tag:Ea5VHJPJE/qwDkbzJuYWgA==,type:str]
kind: Secret
metadata:
    name: credentials
    namespace: observability
sops:
    age:
        - recipient: age1xcavq2xfqzvr6jr0amr2axjgjrn70v5fd9gs8mpu7yzvc297pucscxd252
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbm81VTVzVVNsZExIS0g1
            UU9jV3BRQ1FvdHdZRHV5NWp2VnVFOU41U1ZNCmZVOEo4MFdwaVQxNTN5djFjQU9N
            cVY4MGtsbkVVS1JSbkVYNUpCSCtoN3MKLS0tIEMzbDh3Qi84TDVRNHNjK0hKd0hm
            M3BpY3VuMWxnZVBmVmV6SUg5RS8vTWMKyzP0MxstC1zlCUOQMIzOL775SVj6a+Vs
            Neg5JiGurP3plrOrURTU8iJ7sDaVsBTmPK59MijegNWRv8+7FEHiAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T07:38:33Z"
    mac: ENC[AES256_GCM,data:ztx/pAjFxQVKv7kmdtUFPAAzhsOiyvFCNuyocdA3K66qhjCaF4SdWd5ksrsgyuAr6h0RAcnIddchbaCvJQ7kE+MZSZqtK0zzyXRzwtb3NzmcQVAtnJknam0RBb8Q0fJgcUqG4M5TccMtANEZViO+flnr8gSI1/S8ghVqdci1Lic=,iv:U0p8sCrUIcAfqJnJisOedktWs6Gkr8zWuePGkJlRVjg=,tag:LSMr0QWQihHerGaXLVHkIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
