---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/infrastructure/controllers/alloy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: wait
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables
  decryption:
    provider: sops
    secretRef:
      name: sops-age
#---
## yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: alloy-instance
#  namespace: flux-system
#spec:
#  interval: 1h
#  path: ./k8s/infrastructure/controllers/alloy/instance
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  wait: true
#  postBuild:
#    substituteFrom:
#      - kind: ConfigMap
#        name: variables
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
