---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name topolvm
  namespace: topolvm-system
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: *name
      version: 15.8.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: *name
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 1

    scheduler:
      podDisruptionBudget:
        enabled: false

    storageClasses:
      - name: topolvm-provisioner
        storageClass:
          fsType: xfs
          isDefaultClass: true
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
