apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s-helmrepository.yaml
  - victoria-metrics
  - fluent-bit
  - cnpg
  - plugin-barman-cloud/ks.yaml
  - cilium/ks.yaml
